config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  namespace :pages do
    get "index"
    get "stats"
  end

  # "www.skillm.com/allocate/32" # No idea what this is. Added by Nick.

  get 'users/:user_id/replace_team_role/:id', to: 'team_roles#replace', as: :replace_team_role

  devise_for :users
  resources :users, except: [:new, :create, :destroy] do
    resources :user_skills, only: [:new, :create, :index]
  end

  resources :user_skills, except: [:new, :create] do
    member do
      patch "manager_assessment_update"
    end
  end

  resources :skills

  resources :teams do
    resources :team_roles, except: [:index, :show] do
      resources :team_role_skills, only: [:create, :destroy]
    end
  end
  resources :team_roles, only: [:index]

  namespace :charts do
    get "most_common_skills"
    get "least_common_skills"
    get "occupation"
    get "empty_positions"
    get "most_needed_skills"
    get "less_needed_skills"
  end
end

# Models and controllers generation
#
# rails generate model UserSkill self_assessment:integer manager_assessment:integer self_comment:text manager_comment:text experience:text user:references skill:references
# rails generate model Skill name:string description:text skill_category:references
# rails generate model Skill name:string description:text skill_category:references
# rails generate model SkillCategory name:string
# rails generate model Site country:string city:string
# rails generate model Team name:string description:text owner_contact:string site:references manager:references
# rails generate model TeamRole occupancy:integer name:string team:references
# rails generate model TeamRoleSkill team_role:references skill:references

# rails generate controller users index show edit
# rails generate controller teams index new show edit
# rails generate controller user_skills
# rails generate controller skills index
# rails generate controller team_roles index
# rails generate controller team_role_skills

app/models/user.rb
class User < ApplicationRecord
  include PgSearch
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :site
  belongs_to :manager, class_name: "User", foreign_key: :manager_id, optional: true
  has_many :managed_teams, class_name: "Team", foreign_key: :team_manager_id, dependent: :destroy
  has_many :team_roles, dependent: :destroy
  # has_many :team_role_skills, through: :team_roles
  has_many :teams, through: :team_roles
  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :network_id, presence: true, uniqueness: true
  validates :job_title, presence: true
  validates :chapter, presence: true
  validates :availability, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }, allow_empty: false
  validates :is_manager, inclusion: { in: [true, false] }
  validates :site, presence: true
  validate :verify_manager
  validates :gender, inclusion: { in: [nil, "M", "F"]}

  mount_uploader :photo, PhotoUploader

  def verify_manager
    if self.job_title != "Chapter Lead" && manager.nil?
      errors.add(:manager, "This user needs a manager because the job title is different from the 'Chapter Lead'.")
    end
  end

  def fullname
    "#{first_name} #{last_name}"
  end

  def employees
    is_manager ? User.where(manager_id: id) : []
  end

  def occupation
    occupation_sum = 0
    team_roles.each do |user_role|
      occupation_sum += user_role.occupancy
    end
    return occupation_sum
  end

  pg_search_scope :search_user_by_skill,
    associated_against: { skills: [:name] }
    # ,using: { :tsearch { prefix: true } }
    # will description yield duplicate results?
    # do we add team_roles later?

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  def index
    @users = User.all.order("first_name ASC")
    render layout: "index"
  end

  # def fullname
  #   return "#{user.first_name} #{user.last_name}".join
  # end

  def show
    @user = User.find(params[:id])
    @userskills = UserSkill.all.select do |userskill|
      userskill.user == @user
    end
     @userskills = @userskills.sort_by{|userskill| - userskill.self_assessment}
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "The profile has been updated"
    else
      flash[:alert] = 'Unable to update the profile'
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :network_id, :job_title, :chapter, :availability, :manager_id, :is_manager, :photo, :site_id)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/views/users/_user_skills.html.erb
<h3 class="mb-3 mt-5">Super powers</h3>

<% if @user == current_user %>
  <div class="card p-3 w-100 mb-1">
    <div class="d-flex justify-content-between align-items-center">
      <div>
        <%= link_to new_user_user_skill_path(@user) do %>
          <h5 class="m-0 p-0"> Add a new skill to your profile </h5>
        <% end %>
      </div>

      <div>
        <%= link_to new_user_user_skill_path(@user), class: "btn btn-primary" do %>
          <i class="fas fa-plus"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% @userskills.each do |userskill| %>
  <div class="card p-3 w-100 mb-1">
    <div class="d-flex justify-content-between align-items-center">

      <div class="profile-rating-width">
        <h5 class="mb-2">
          <%= userskill.skill.name %>
            <% userskill.self_assessment.times do %>
            <i class="fas fa-star text-info"></i>
          <% end %>
        </h5>
        <p><i class="fas fa-comment text-secondary"></i>  <%= userskill.self_comment %></p>
        <% if @user == current_user || current_user.is_manager%>
         <p>
          <strong> Manager's perspective:  </strong>
          <% unless userskill.manager_assessment.nil? %>
            <% userskill.manager_assessment.times do %>
            <i class="fas fa-star text-info"></i>
          <% end %>
          </p>
          <p class="m-0"><i class="fas fa-comments text-secondary"></i>  <%= userskill.manager_comment %></p>
          <% end %>
        <% end %>
      </div>

      <div class="w-30 team-name-width">
        <h5>Experience</h5>
        <%= userskill.experience %>
      </div>

      <div class="flex-column text-align-right">
        <% if @user == current_user %>
          <%= link_to  user_skill_path(userskill), data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-primary ml-4" do %>
            <i class="fas fa-trash-alt"></i>
          <% end %>
        <% end %>
        <% if @user == current_user || current_user.is_manager %>
          <%= link_to edit_user_skill_path(userskill.id), class: "btn btn-primary ml-2" do %>
            <i class="fas fa-pen"></i>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
<% end %>

app/views/users/_user_team_roles.html.erb
<h3 class="mb-3 mt-5">Assignments</h3>

  <div class="card p-3 w-100 mb-1">
    <div class="d-flex justify-content-between align-items-center">
      <div>
        <%= link_to teams_path(user_id: @user) do %>
          <h5 class="mb-0"> Allocate <%= @user.first_name %> to a new team </h5>
        <% end %>
      </div>

      <div>
        <%= link_to teams_path(user_id: @user), class: "btn btn-primary" do %>
          <i class="fas fa-plus"></i>
        <% end %>
      </div>
    </div>
  </div>

<% @user.team_roles.each do |team_role| %>
  <div class="card p-3 w-100 mb-1">
    <div class="d-flex justify-content-between align-items-center">

      <div class="team-role-width">
        <%= link_to team_role.name, team_path(team_role.team) %>
      </div>

      <div class="team-name-width">
        <%= link_to team_role.team.name, team_path(team_role.team) %>
      </div>

      <div>
        <%= team_role.occupancy %> %
      </div>

      <div class="flex-column text-align-right">
        <% if @user == current_user || current_user.is_manager %>
          <%= link_to edit_team_team_role_path(team_role.team, team_role), class: "btn btn-primary" do %>
              <i class="fas fa-pen"></i>
            <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
  <h3>Update my profile</h3>
  <%= link_to teams_path, class: "btn btn-secondary" do %>
      <i class="fas fa-undo-alt mr-2"></i> my profile
    <% end %>
  </div>

  <%= simple_form_for(@user) do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :network_id %>
    <%= f.input :job_title %>
    <%= f.input :chapter %>
    <%= f.input :availability, input_html: { min: 1, max: 100 }  %>
    <%= f.input :is_manager, as: :select %>
    <%= f.association :manager, label_method: :fullname, value_method: :id, include_blank: false%>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.association :site, as: :select, label_method: :city, value_method: :id, include_blank: false %>
    <%= f.button :submit, class: "btn btn-primary" %>
  <% end %>

  </div>

app/views/users/index.html.erb
<div class="container people-banner home-wrapper">
  <div class="container d-flex align-items-center">
      <div class="ml-4"><h3>People</h3></div>
  </div>
</div>

<div class="container pb-5 pt-4 mt-0 container-background">

  <ul class="list-group">
    <% @users.each do |user| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <p class="team-role-details-width mb-0"> <%= link_to "#{user.first_name} #{user.last_name}  (#{user.job_title}) ", user_path(user) %> </p>
        <div mt-2 mb-2>
          <% a = user.availability %>
          <% o = user.occupation %>
          <% if a == o %>
            <i class="fas fa-check-circle text-secondary"></i>
          <% elsif a > o  %>
            <span class="text-success"> <%= user.availability - user.occupation %>% free </span>
          <% else %>
            <span class="text-primary">  <i class="fas fa-exclamation-circle"></i> <%= user.occupation - user.availability %>% overload </span>
          <% end %>
        </div>


        <% if user.is_manager == true %>
          <span class="badge badge-danger badge-pill"> Mgr </span>
        <% else %>
          <span class="badge badge-transparent badge-pill"> </span>
        <% end %>

        <% if user.user_skills.all.count > 0 %>
          <span class="pills badge badge-primary badge-pill"><%= user.user_skills.all.count %></span>
          <% else %>
          <span class="pills badge badge-secondary badge-pill"><%= user.user_skills.all.count %></span>
        <% end %>
      </li>
    <% end %>
  </ul>

</div>

app/views/users/show.html.erb
<div class="d-flex justify-content-between align-items-center mb-3">
  <h3><%= @user.first_name %> <%= @user.last_name %></h3>
  <%= link_to users_path, class: "btn btn-secondary" do %>
  <i class="fas fa-undo-alt"></i> All co-workers
  <% end %>
</div>

  <div class="d-flex card p-3 mb-3 mr-3 user-details">
    <div class="d-flex justify-content-between align-items-center">
      <div>
        <%= cl_image_tag(@user.photo, width: 250, height: 250, crop: :thumb, gravity: :face) %>
      </div>

      <div>
        <p> <strong> <i class="fas fa-network-wired text-secondary"></i> Job title: </strong> <%= @user.job_title %></p>
        <div class="d-flex mt-5">
          <div class="mr-4">
            <% total_occupation = @user.occupation %>
            <p class="text-center mb-2"> <strong> Weekly hours </strong> </p>
            <h3 class="text-center"> <i class="far fa-circle text-secondary"></i> <%= ( 0.4 * @user.availability ).round %>h </h3>
          </div>
          <div>
            <p class="text-center mb-2"> <strong>  Allocated for </strong> </p>
            <h3 class="text-center"> <i class="fas fa-circle text-secondary"></i>  <%= total_occupation %>% </h3>
          </div>
        </div>
        <div class="d-flex">
          <% if @user.availability < total_occupation %>
          <h4 class="text-center text-primary mt-4"><i class="fas fa-exclamation-circle"></i> <%= total_occupation - @user.availability %>% overload</h4>
          <% end %>
        </div>
      </div>

      <div>
        <p> <strong> <i class="fas fa-users text-secondary"></i> Chapter: </strong> <%= @user.chapter %></p>

        <%# Dirty hack to fix the manager issue for 1st person in the database %>
        <% if @user.job_title != "Chapter Lead" %>
          <% if @user.is_manager == "true" %>
            <p> <strong> <i class="fas fa-user-tie text-secondary"></i> Manager: </strong> Yes </p>
          <% else %>
            <p> <strong> <i class="fas fa-user-tie text-secondary"></i> Manager: </strong> <%= link_to "#{@user.manager.first_name} #{@user.manager.last_name}", user_path(@user.manager) %></p>
          <% end %>
        <% end %>
        <p> <strong> <i class="fas fa-building text-secondary"></i> </strong> <%= @user.site.country %>, <%= @user.site.city %></p>
        <p><strong><i class="fas fa-at text-secondary"></i> </strong> <%= @user.email %></p>
        <p><strong><i class="fas fa-id-card-alt text-secondary"></i></strong> <%= @user.network_id %></p>
      </div>
      <div>
        <% if @user == current_user %>
          <%= link_to edit_user_path, class: "btn btn-primary w-100" do %>
            <i class="fas fa-pen"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

<%= render 'user_team_roles' %>

<%= render 'user_skills' %>