config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  namespace :pages do
    get "index"
    get "stats"
  end

  # "www.skillm.com/allocate/32" # No idea what this is. Added by Nick.

  get 'users/:user_id/replace_team_role/:id', to: 'team_roles#replace', as: :replace_team_role

  devise_for :users
  resources :users, except: [:new, :create, :destroy] do
    resources :user_skills, only: [:new, :create, :index]
  end

  resources :user_skills, except: [:new, :create] do
    member do
      patch "manager_assessment_update"
    end
  end

  resources :skills

  resources :teams do
    resources :team_roles, except: [:index, :show] do
      resources :team_role_skills, only: [:create, :destroy]
    end
  end
  resources :team_roles, only: [:index]

  namespace :charts do
    get "most_common_skills"
    get "least_common_skills"
    get "occupation"
    get "empty_positions"
    get "most_needed_skills"
    get "less_needed_skills"
  end
end

# Models and controllers generation
#
# rails generate model UserSkill self_assessment:integer manager_assessment:integer self_comment:text manager_comment:text experience:text user:references skill:references
# rails generate model Skill name:string description:text skill_category:references
# rails generate model Skill name:string description:text skill_category:references
# rails generate model SkillCategory name:string
# rails generate model Site country:string city:string
# rails generate model Team name:string description:text owner_contact:string site:references manager:references
# rails generate model TeamRole occupancy:integer name:string team:references
# rails generate model TeamRoleSkill team_role:references skill:references

# rails generate controller users index show edit
# rails generate controller teams index new show edit
# rails generate controller user_skills
# rails generate controller skills index
# rails generate controller team_roles index
# rails generate controller team_role_skills

app/models/skill.rb
class Skill < ApplicationRecord
  include PgSearch
  belongs_to :skill_category
  has_many :user_skills, dependent: :destroy
  has_many :team_role_skills, dependent: :destroy
  has_many :users, through: :user_skills # in order to show all users with a particular skill
  has_many :team_roles, through: :team_role_skills # in order to show all placeholders in need of a particular skill
  has_many :team, through: :team_roles # in order to show all teams that are working with a skill
  validates :name, presence: true, uniqueness: true
  # validates :description

  pg_search_scope :search_by_skillname, against: :name




end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  def index
    # @skills = Skill.all
    @skills = Skill.all.order("name ASC")
    render layout: "index"
  end

  def new
    @skill = Skill.new
  end

  def create
    @skill = Skill.new(skills_params)
    if @skill.save
      redirect_to skills_path, notice: "#{@skill.name} skill has been added"
    else
      flash[:alert] = 'Unable to create the skill'
      render :new
    end
  end

  def edit
    @skill = Skill.find(params[:id])
  end

  def update
    @skill = Skill.find(params[:id])
    if @skill.update(skills_params)
      redirect_to skills_path, notice: "#{@skill.name} skill has been updated"
    else
      flash[:notice] = 'Unable to update the skill'
      render :edit
    end
  end

  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy
    redirect_to skills_path, notice: "#{@skill.name} skill has been deleted"
  end

  private

  def skills_params
    params.require(:skill).permit(:name, :description, :skill_category_id)
  end
end

app/views/skills/_skill_form.html.erb
<%= simple_form_for(@skill) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.association :skill_category, label_method: :name, value_method: :id, include_blank: false %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/skills/edit.html.erb
<div class="container">
  <h1>Edit skill <%= @skill.name %></h1>
  <%= render 'skill_form' %>
  <hr>
  <%= link_to "Back to the list", skills_path %>
</div>

app/views/skills/index.html.erb
<div class="container skills-banner home-wrapper">
  <div class="container d-flex align-items-center">
      <div class="ml-4"><h3>Skills Inventory</h3></div>
  </div>
</div>

<div class="container pb-5 pt-4 mt-0 container-background">

  <% if current_user.is_manager %>
    <div class="pl-3 mb-4">
      <%= link_to new_skill_path do %>
        <div class="btn btn-flat btn-info text-white"><i class="fas fa-plus"></i> <strong>New skill</strong> </div>
      <% end %>
    </div>
  <% end %>

  <div class="d-flex flex-wrap">
  <% @skills.each do |skill|%>

    <div class="d-flex flex-row border-0 mt-3 mb-3 skill-inventory-card border-0" type="button" class="btn btn-secondary" data-toggle="tooltip" data-html="true" title="<%= skill.description %>">
      <% if current_user.is_manager %>
        <div class="p-2">
          <%= skill.name %>
        </div>
        <div class="p-2">
          <%= link_to edit_skill_path(skill) do %>
            <i class="fas fa-pen"></i>
          <% end %>
        </div>
        <div class="p-2">
          <%= link_to skill_path(skill), data: { confirm: "Are you sure you want to delete #{skill.name} skill? It will also be deleted from all profiles and teams." }, method: :delete do %>
          <i class="fas fa-trash-alt"></i>
          <% end %>
        </div>
      <% end %>

    </div>

   <% end %>
  </div>

</div>

app/views/skills/new.html.erb
<div class="container">
  <h1>Create new skill</h1>
  <%= render 'skill_form' %>
  <hr>
  <%= link_to skills_path do %>
    <i class="fas fa-undo-alt"></i> Skills list
  <% end %>
</div>