config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  namespace :pages do
    get "index"
    get "stats"
  end

  # "www.skillm.com/allocate/32" # No idea what this is. Added by Nick.

  get 'users/:user_id/replace_team_role/:id', to: 'team_roles#replace', as: :replace_team_role

  devise_for :users
  resources :users, except: [:new, :create, :destroy] do
    resources :user_skills, only: [:new, :create, :index]
  end

  resources :user_skills, except: [:new, :create] do
    member do
      patch "manager_assessment_update"
    end
  end

  resources :skills

  resources :teams do
    resources :team_roles, except: [:index, :show] do
      resources :team_role_skills, only: [:create, :destroy]
    end
  end
  resources :team_roles, only: [:index]

  namespace :charts do
    get "most_common_skills"
    get "least_common_skills"
    get "occupation"
    get "empty_positions"
    get "most_needed_skills"
    get "less_needed_skills"
  end
end

# Models and controllers generation
#
# rails generate model UserSkill self_assessment:integer manager_assessment:integer self_comment:text manager_comment:text experience:text user:references skill:references
# rails generate model Skill name:string description:text skill_category:references
# rails generate model Skill name:string description:text skill_category:references
# rails generate model SkillCategory name:string
# rails generate model Site country:string city:string
# rails generate model Team name:string description:text owner_contact:string site:references manager:references
# rails generate model TeamRole occupancy:integer name:string team:references
# rails generate model TeamRoleSkill team_role:references skill:references

# rails generate controller users index show edit
# rails generate controller teams index new show edit
# rails generate controller user_skills
# rails generate controller skills index
# rails generate controller team_roles index
# rails generate controller team_role_skills

app/views/pages/home.html.erb
<div class="home-wrapper">

<div class="banner">
   <div class="container d-flex justify-content-center flex-column align-items-center mt-5">

      <div class="navbar-home mb-4">
        <%= link_to root_path, class: "home-brand mb-4" do %>
        <%= image_tag "logo02.png" %>
        <% end %>

<!--         <div class="home-brandtext text-white">
          <p><em><strong>SkillM</strong></em></p>
        </div>
      </div> -->


      <div class="mt-5 text-center">
        <!-- <h1>Find the best person for the job </h1> -->
        <h1> Build qualified teams with SkillM</h1>
      </div>

      <form action="/pages/index" method="GET" class="position-relative">
        <select class="query-select-boxes" name="query[]" multiple="multiple" style="width: 75%" id="select2Selector">
          <% @skills.each do |skill| %>
          <option value="<%= skill.name %>"><%= skill.name %></option>
          <% end %>
        </select>
        <button id = "searchbutton_home" name="button" type="submit" class="btn btn-flat btn-dark">
          <i class="fas fa-search"></i>
        </button>
      </form>

      <div class="d-flex mt-5 pt-2 w-100 justify-content-start home-links">

        <p class="nav-item mr-2">
          <%= link_to "People", users_path, class: "nav-link text-white" %>
        </p>

        <p class="nav-item mr-2">
          <%= link_to "Teams", teams_path, class: "nav-link text-white" %>
          </<%=  %>>

          <p class="nav-item mr-2">
            <%= link_to "Open spots", team_roles_path, class: "nav-link text-white" %>
          </p>

          <p class="nav-item mr-2">
            <%= link_to "Skills", skills_path, class: "nav-link text-white" %>
          </p>

          <p class="nav-item mr-2">
            <%= link_to "Dashboard", pages_stats_path, class: "nav-link text-white" %>
          </p>

        </div>
      </div>

    </div>

  </div>

app/views/pages/index.html.erb
<div class="container people-banner home-wrapper">
  <div class="container">

    <div class="pl-5">
      <div id="search_bar">
        <form action="/pages/index" method="GET" class="">
          <select class="query-select-boxes" name="query[]" multiple="multiple" style="width: 75%" id="select2Selector">
           <% @skills.each do |skill| %>
            <option value="<%= skill.name %>"><%= skill.name %></option>
           <% end %>
           </select>
           <button id = "searchbutton_index" name="button" type="submit" class="btn btn-flat btn-dark">
              <i class="fas fa-search"></i>
           </button>
          </form>
      </div>
    </div>
  </div>
</div>

<div class="container pb-5 mb-0 container-background">
  <h5 class="pt-4 mb-0 pl-3"> <%= pluralize(@users.count, 'person')  %> found: </h5>
  <div class="flex-container cards-wrapper mt-0">
  <% if params[:query].present? %>
    <% unless !params[:query].is_a?(Array) && params.dig(:query, :team_role_id)  %>
      <div class="card card_placeholder">
        <div class="card-body p-3">
          <div class="d-flex user-head-placeholder">
            <%= image_tag "avatar_placeholder2.jpg", alt: "placeholder", class: "avatar" %>

          </div>
          <div><h5 class="card-title"> <br> No match found? </h5></div>
          <p class="mb-2"> <strong>Your need:</strong></p>

          <div class="card-text mb-2">
            <% @queryskills.each do |value| %>
            <p class="ml-2"> <i class="fas fa-search"></i> <%= value %> </p>
           <% end %>
         </div>
           <%= link_to teams_path(placeholder: true, query_array: @queryskills ) do %>
             <p class="btn btn-info text-white w-100 mb-2 btn-placeholder"><i class="fas fa-plus mr-2"></i> Save search </p>
           <% end %>
         </div>
      </div>
    <% end %>
  <% end %>

    <% @users.each do |user| %>
    <div class="card card_details">
      <div class="card-body p-3">
        <div class="d-flex user-head">
            <%= link_to user_path(user) do %>
              <div class="avatar" style="background-image: url('<%= cl_image_path user.photo, width: 50, height: 50, crop: :thumb, gravity: :face %>')"></div>
            <% end %>
            <div class="ml-2">
              <% fullname = "#{user.first_name} #{user.last_name}" %>
              <% if fullname.length > 16 %>
                <h6 class="card-title mb-1 text-muted"><%= link_to user_path(user) do %>
                   <%= fullname[0...14] %>...
                   <% end %>
                </h6>
                <% else %>
                <h6 class="card-title mb-1 text-muted"><%= link_to user_path(user) do %>
                   <%= fullname %>
                   <% end %>
                  <% end %>
                </h6>
              <% if user.job_title.length > 20 %>
                <small class="card-subtitle mb-1"><em><%= user.job_title[0...17] %>...</em></small> <br />
              <% else %>
                <small class="card-subtitle mb-1"><em><%= user.job_title %></em></small> <br />
              <% end %>
              <small class="card-subtitle mb-3 text-muted"><em>Allocatable for</em></small>
              <% total_occupancy = 0 %>
              <% user.team_roles.each do |team| %>
                <% total_occupancy += team.occupancy %>
              <% end %>
              <small class="card-subtitle "><strong><%= user.availability - total_occupancy %>% </strong></small>

            </div>
        </div>
        <div class="card-text-team mb-2 mt-2">
        <% user.teams.each do |team| %>
            <% if team.name.length > 18 %>
             <li><i class="fas fa-users text-secondary mb-2"></i> <%= team.name[0...16] %>...</li>
           <% else %>
             <li><i class="fas fa-users text-secondary mb-2"></i> <%= team.name %></li>
          <% end %>
        <% end %>
        </div>
       <div class="card-text mb-3">
        <% user.user_skills.sort_by{|userskill| -userskill.self_assessment}.each do |userskill| %>
          <% if @queryskills.include? userskill.skill.name %>
            <p><i class="fas fa-star text-info"></i> <%= userskill.self_assessment %>
              <% if current_user.is_manager %>
                (<i class="fas fa-user-tie text-secondary"></i> <%= userskill.manager_assessment%>)
              <% end %>
              <%= userskill.skill.name %> </p>
          <% elsif @queryskills_pg.include? userskill.skill.name %>
            <p class="text-secondary"><i class="fas fa-star text-info"></i> <%= userskill.self_assessment %>
              <% if current_user.is_manager %>
                (<i class="fas fa-user-tie"></i> <%= userskill.manager_assessment%>)
              <% end %>
              <%= userskill.skill.name %> </p>
         <% end %>
        <% end %>
       </div>

        <% if !params[:query].is_a?(Array) && params.dig(:query, :team_role_id).present? %>
          <%= link_to replace_team_role_path(user, @team_role) do %>
            <p class="btn btn-primary w-100 mb-2 button-upgrade"> Fill open spot </p>
          <% end %>
        <% else %>
          <%= link_to teams_path(user_id: user) do %>
            <p class="btn btn-primary w-100 mb-0 button-upgrade"><i class="fas fa-plus mr-2"></i> Allocate</p>
          <% end %>
        <% end %>

      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/pages/stats.html.erb
<!-- <div class="mx-5 home-wrapper pt-3 px-4 container-background"> -->
  <%# <div class="stats-banner mb-4">
    <div class="container d-flex align-items-center">
      <div class="mr-4"><h2>Charts and data</h2></div>
    </div>
  </div> %>

  <div class="row">
    <div class="col-6">
      <div class="card mt-2 ml-4 border-0 p-4" style="height: 21rem;">
        <h5 class="text-primary">Dashboard</h5>
          <div class="d-flex justify-content-around">
            <div class="card border-0 p-3 m-3 chart-box">
              <h5 class="card-title text-center mb-2 text-secondary">People</h5>
              <h3 class="text-center text-primary"> <%= @people %></h3>
            </div>
            <div class="card border-0 p-3 m-3 chart-box">
              <h5 class="card-title text-center mb-2 text-secondary">Teams</h5>
              <h3 class="text-center text-primary"> <%= @teams %></h3>
            </div>
            <div class="card border-0 p-3 m-3 chart-box">
              <h5 class="card-title text-center mb-2 text-secondary">Open spots</h5>
              <h3 class="text-center text-primary"> <%= @empty_count %> </h3>
            </div>
          </div>
          <div class="d-flex justify-content-between">
            <div class="card border-0 p-3 m-3 chart-box">
              <h5 class="card-title text-center mb-2 text-secondary">Allocation rate</h5>
              <h3 class="text-center text-primary mb-2"> <%= @allocation_rate.round %> %</h3>
            </div>
            <div class="card border-0 p-3 m-3  chart-box">
              <h5 class="card-title text-center mb-2 text-secondary">Skills per person</h5>
              <h3 class="text-center text-primary mb-2"> <%= @skills_pp %></h3>
            </div>
          </div>
      </div>
    </div>

    <div class="col-3">
      <div class="card border-0 bg-transparent" style="height: 22rem;">
        <div class="card-body">
          <h5 class="card-title text-center text-primary">Staff allocation rates</h5>
          <%= pie_chart charts_occupation_path, colors: ["#7C1B2D", "#606060", "#964050", "#7C7C7C", "#A8253D", "#AFAFAF"] %>
          <%#= pie_chart charts_occupation_path, colors: ["#dark pink", "#dark gray", "#pink", "#gray", "#light pink", "#light gray"] %>
          <%#= pie_chart charts_occupation_path, colors: ["#A4243B", "#FFA524", "#7D1128", "#606060", "#0A8A00"] %>
          <%#= pie_chart charts_occupation_path, colors: ["#pink", "#yellow", "#red", "#gray", "#green"] %>
        </div>
      </div>
    </div>

    <div class="col-3">
      <div class="card border-0 bg-transparent" style="height: 22rem;">
        <div class="card-body">
          <h5 class="card-title text-center text-primary">Open vs filled spots</h5>
          <%= pie_chart charts_empty_positions_path, colors: ["#7C1B2D", "#606060", "#964050", "#7C7C7C", "#A8253D", "#AFAFAF"] %>
        </div>
      </div>
    </div>

  </div>

  <div class="row">

    <div class="col-6">
      <div class="card my-3 border-0 bg-transparent">
        <div class="card-body">
          <h5 class="card-title text-primary">Top 10 common skills</h5>
          <%= column_chart charts_most_common_skills_path, colors: ["#606060", "#333333"] %>
        </div>
      </div>
    </div>

    <div class="col-6">
      <div class="card my-3 border-0 bg-transparent">
        <div class="card-body">
          <h5 class="card-title text-primary">Top 10 needed skills for open spots</h5>
          <%= column_chart charts_most_needed_skills_path, colors: ["#A4243B", "#333333"] %>
        </div>
      </div>
    </div>

  </div>


  <%
=begin %>
  <div class="row">
    <div class="col">
      <div class="card my-3">
        <div class="card-body">
          <h5 class="card-title">Least common skills</h5>
          <%= column_chart charts_least_common_skills_path, colors: ["#A4243B", "#333333"] %>
        </div>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="card my-3">
      <div class="card-body">
        <h5 class="card-title">10 less needed skills for empty roles</h5>
        <%= column_chart charts_less_needed_skills_path, colors: ["#FFA524", "#333333"] %>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="card my-3">
      <div class="card-body">
        <h5 class="card-title">Empty and taken positions</h5>
        <%= pie_chart charts_empty_positions_path, colors: ["#167FFB", "#FFA524", "#0A8A00", "#F5F5F5", "#333333","#A4243B", "#7D1128" ] %>
      </div>
    </div>
  </div>
<%
=end %>