config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  namespace :pages do
    get "index"
    get "stats"
  end

  # "www.skillm.com/allocate/32" # No idea what this is. Added by Nick.

  get 'users/:user_id/replace_team_role/:id', to: 'team_roles#replace', as: :replace_team_role

  devise_for :users
  resources :users, except: [:new, :create, :destroy] do
    resources :user_skills, only: [:new, :create, :index]
  end

  resources :user_skills, except: [:new, :create] do
    member do
      patch "manager_assessment_update"
    end
  end

  resources :skills

  resources :teams do
    resources :team_roles, except: [:index, :show] do
      resources :team_role_skills, only: [:create, :destroy]
    end
  end
  resources :team_roles, only: [:index]

  namespace :charts do
    get "most_common_skills"
    get "least_common_skills"
    get "occupation"
    get "empty_positions"
    get "most_needed_skills"
    get "less_needed_skills"
  end
end

# Models and controllers generation
#
# rails generate model UserSkill self_assessment:integer manager_assessment:integer self_comment:text manager_comment:text experience:text user:references skill:references
# rails generate model Skill name:string description:text skill_category:references
# rails generate model Skill name:string description:text skill_category:references
# rails generate model SkillCategory name:string
# rails generate model Site country:string city:string
# rails generate model Team name:string description:text owner_contact:string site:references manager:references
# rails generate model TeamRole occupancy:integer name:string team:references
# rails generate model TeamRoleSkill team_role:references skill:references

# rails generate controller users index show edit
# rails generate controller teams index new show edit
# rails generate controller user_skills
# rails generate controller skills index
# rails generate controller team_roles index
# rails generate controller team_role_skills

app/models/team_role.rb
class TeamRole < ApplicationRecord
  belongs_to :team
  belongs_to :user, optional: true
  has_many :team_role_skills, dependent: :destroy
  has_many :skills, through: :team_role_skills
  validates :name, presence: true
  validates :team, presence: true
  validates :occupancy, presence: true, inclusion: { in: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] }

  def self.occupancy_rates
    [20, 30, 40, 50, 60, 70, 80, 90, 100]
  end
end

app/controllers/team_roles_controller.rb
class TeamRolesController < ApplicationController
  before_action :find_team_role, only: [:edit, :update, :destroy]
  before_action :find_team, only: [:new, :create, :edit, :update, :destroy]

  def index
    @team_roles = TeamRole.all.order(updated_at: :desc)
    render layout: "index"
  end

  def replace
    @team_role = TeamRole.find(params[:id])
    @user = User.find(params[:user_id])
    @team_role.user = @user
    @team_role.save
    redirect_to team_path(@team_role.team)
  end

  def new
    @team_role = TeamRole.new
    @query_array = params[:query_array]
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @team_role.user = @user
    end
  end

  def create
    @team_role = TeamRole.new(team_role_params)
    @team_role.team = @team

    # if params[:team_role][:user_id].present?
    #   @user = User.find(params.dig(:team_role, :user_id))
    #   if @team_role.occupancy > 100 - @user.occupation
    #     flash[:alert] = "#{@user.first_name} #{@user.last_name} is available only for #{100 - @user.occupation}% of time."
    #     render :new
    #     return
    #   end
    # end
    if @team_role.save
      if params[:query_array].present?
        params[:query_array].split("\%\%\%").each do |searched_skill|
          skill = Skill.find_by(name: searched_skill)
          TeamRoleSkill.create(team_role: @team_role, skill: skill)
        end
      end
      redirect_to team_path(@team, query_array: params[:query_array]), notice: "#{@team_role.name} role has been added to the #{@team.name} team"
    else
      flash[:alert] = 'Unable to create the role'
      render :new
    end
  end

  def edit
    @team_role_skill = TeamRoleSkill.new
  end

  def update
    # @user = User.find(params.dig(:team_role, :user_id))
    # if @team_role.occupancy > 100 - @user.occupation
    #   flash[:alert] = "#{@user.first_name} #{@user.last_name} is available only for #{100 - @user.occupation}% of time."
    #   render :edit
    #   return
    # else
      if @team_role.update(team_role_params)
        redirect_to team_path(@team), notice: "#{@team_role.name} role has been updated"
      else
        flash[:alert] = 'Unable to update the role'
        render :edit
      end
    # end
  end

  def destroy
    @team_role.destroy
    redirect_to team_path(@team), notice: "#{@team_role.name} role has been deleted from the #{@team.name} team"
  end

  private


  def team_role_params
    params.require(:team_role).permit(:name, :occupancy, :user_id)
  end

  def find_team_role
    @team_role = TeamRole.find(params[:id])
  end

  def find_team
    @team = Team.find(params[:team_id])
  end
end

app/views/team_roles/_team_role_form.html.erb
<%= simple_form_for [@team, @team_role] do |f| %>
  <%= f.error :base %>
  <%= f.input :name, label: "Give the new role a name, e.g. Lead Backend Programmer" %>
  <% unless params[:placeholder] && params[:user].present? %>
    <%= f.association :user, label_method: :fullname, label: "OPTIONAL: Choose co-worker or leave it for later, creating a open spot for now"%>
  <% end %>
  <%= f.input :occupancy, collection: TeamRole.occupancy_rates, label: "Add allocation percentage (size in \%)" %>
  <%= hidden_field_tag :query_array, @query_array.join("\%\%\%") if @query_array%>
  <%= f.button :submit, class: "btn btn-primary", value: "Save" %>
<% end %>

app/views/team_roles/_team_role_list_filled.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <p class="mb-0 team-name-width"> <%= link_to team_role.name, team_path(team_role.team) %> <br>( <%= team_role.occupancy%> %) </p>
  <p class="mb-0 team-name-width"> <%= link_to team_role.team.name, team_path(team_role.team) %> </p>

  <div class="d-flex team-role-details-width align-items-center">
    <%= link_to user_path(team_role.user) do%>
    <div class="avatar mr-2" style="background-image: url('<%= cl_image_path team_role.user.photo, width: 50, height: 50, crop: :thumb, gravity: :face %>')"></div>
    <% end %>

    <%= link_to user_path(team_role.user) do%>
    <div class="d-flex align-items-center">
      <%= team_role.user.first_name %> <%= team_role.user.last_name %>
    </div>
  </div>
<% end %>
  <span class="badge badge-success badge-pill"> Filled </span>
</li>

app/views/team_roles/_team_role_list_open.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <p class="mb-0 team-name-width"> <%= link_to team_role.name, team_path(team_role.team) %> <br>( <%= team_role.occupancy%> %) </p>
  <p class="mb-0 team-name-width"> <%= link_to team_role.team.name, team_path(team_role.team) %> </p>

  <div class="p-3 team-role-details-width ">
    <% team_role.team_role_skills.each do |team_role_skill| %>
    * <%= team_role_skill.skill.name %>
    <% end %>
  </div>

  <span class="badge badge-danger badge-pill"> Open </span>
</li>

app/views/team_roles/_team_role_skill_form.html.erb
<%= simple_form_for [@team, @team_role, @team_role_skill] do |f| %>
  <%= f.association :skill, label: false %>
  <%= f.button :submit, "Add skill", class: "btn btn-primary"%>
<% end %>

app/views/team_roles/edit.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
  <h3>Update team role details in team "<%= @team.name %>"</h3>
  <%= link_to team_path(@team), class: "btn btn-secondary" do %>
      <i class="fas fa-undo-alt mr-2"></i> Team
    <% end %>
  </div>

  <%= render 'team_role_form' %>

<hr>


  <%= link_to "Delete the team role", team_team_role_path(@team, @team_role), method: :delete, data: { confirm: "Are you sure you want to delete #{@team_role.name} role from #{@team.name} team? All linked skills will be also deleted." }, class: "btn btn-danger" %>

</div>

app/views/team_roles/index.html.erb
<div class="container people-banner home-wrapper">
  <div class="container d-flex align-items-center">
    <div class="ml-4">
      <h3>Open Spots</h3>
    </div>
  </div>
</div>

<div class="container pb-5 pt-4 mt-0 container-background">

  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="pills-open-tab" data-toggle="pill" href="#pills-open" role="tab"
        aria-controls="pills-open" aria-selected="true">Open</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="pills-filled-tab" data-toggle="pill" href="#pills-filled" role="tab"
        aria-controls="pills-filled" aria-selected="false">Filled</a>
    </li>
  </ul>

  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="pills-open" role="tabpanel" aria-labelledby="pills-open-tab">

      <ul class="list-group">
        <% @team_roles.each do |team_role| %>
          <% if team_role.user.nil? %>
            <%= render "team_role_list_open", team_role: team_role %>
          <% end %>
        <% end %>
      </ul>

    </div>

    <div class="tab-pane fade" id="pills-filled" role="tabpanel" aria-labelledby="pills-filled-tab">

      <ul class="list-group">
        <% @team_roles.each do |team_role| %>
          <% if team_role.user != nil %>
            <%= render "team_role_list_filled", team_role: team_role %>
          <% end %>
        <% end %>
      </ul>

    </div>
  </div>
</div>

app/views/team_roles/new.html.erb
<div class="container">
  <div class="d-flex justify-content-between align-items-center">
    <h3 class="mb-4">Add new team role to "<%= @team.name %>"</h3>
    <%= link_to team_path(@team), class: "btn btn-secondary" do %>
      <i class="fas fa-undo-alt mr-2"></i> Team
    <% end %>
  </div>

  <%= render 'team_role_form' %>
</div>